export enum OrganizationVersionServiceCommands {
  GET_LIST_BY_PAGINATION = 'ORGANIZATION_VERSION_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'ORGANIZATION_VERSION_GET_ALL_LIST',
  GET_BY_ID = 'ORGANIZATION_VERSION_GET_BY_ID',
  CREATE = 'ORGANIZATION_VERSION_CREATE',
  CREATED = 'ORGANIZATION_VERSION_CREATED',
  UPDATE = 'ORGANIZATION_VERSION_UPDATE',
  DELETE = 'ORGANIZATION_VERSION_DELETE',
  RESTORE = 'ORGANIZATION_VERSION_RESTORE',
}
