export enum CityServiceCommands {
    GET_LIST_BY_PAGINATION = 'CITY_GET_LIST_BY_PAGINATION',
    GET_ALL_LIST = 'CITY_GET_ALL_LIST',
    GET_BY_ID = 'CITY_GET_BY_ID',
    CREATE = 'CITY_CREATE',
    CREATED = 'CITY_CREATED',
    UPDATE = 'CITY_UPDATE',
    DELETE = 'CITY_DELETE',
    RESTORE = 'CITY_RESTORE',
  }
  
  