export enum SubCategoryServiceCommands {
    GET_LIST_BY_PAGINATION = 'SUB_CATEGORY_GET_LIST_BY_PAGINATION',
    GET_ALL_LIST = 'SUB_CATEGORY_GET_ALL_LIST',
    GET_BY_ID = 'SUB_CATEGORY_GET_BY_ID',
    CREATE = 'SUB_CATEGORY_CREATE',
    CREATED = 'SUB_CATEGORY_CREATED',
    UPDATE = 'SUB_CATEGORY_UPDATE',
    DELETE = 'SUB_CATEGORY_DELETE',
    RESTORE = 'SUB_CATEGORY_RESTORE',
  }
  
  