export enum ProductServiceSubCategoryServiceCommands {
  GET_LIST_BY_PAGINATION = 'PRODUCT_SERVICE_SUB_CATEGORY_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'PRODUCT_SERVICE_SUB_CATEGORY_GET_ALL_LIST',
  GET_BY_ID = 'PRODUCT_SERVICE_SUB_CATEGOR_GET_BY_ID',
  CREATE = 'PRODUCT_SERVICE_SUB_CATEGORY_CREATE',
  CREATED = 'PRODUCT_SERVICE_SUB_CATEGOR_CREATED',
  UPDATE = 'PRODUCT_SERVICE_SUB_CATEGORY_UPDATE',
  DELETE = 'PRODUCT_SERVICE_SUB_CATEGORY_DELETE',
  RESTORE = 'PRODUCT_SERVICE_SUB_CATEGOR_RESTORE',
}
  
  