export enum AdditionalTableServiceCommands {
  GET_LIST_BY_PAGINATION = 'ADDITIONAL_TABLE_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'ADDITIONAL_TABLE_GET_ALL_LIST',
  GET_BY_ID = 'ADDITIONAL_TABLE_GET_BY_ID',
  CREATE = 'ADDITIONAL_TABLE_CREATE',
  UPDATE = 'ADDITIONAL_TABLE_UPDATE',
  DELETE = 'ADDITIONAL_TABLE_DELETE',
  RESTORE = 'ADDITIONAL_TABLE_RESTORE',
}
