export enum LaneServiceCommands {
    GET_LIST_BY_PAGINATION = 'LANE_GET_LIST_BY_PAGINATION',
    GET_ALL_LIST = 'LANE_GET_ALL_LIST',
    GET_BY_ID = 'LANE_GET_BY_ID',
    CREATE = 'LANE_CREATE',
    CREATED = 'LANE_CREATED',
    UPDATE = 'LANE_UPDATE',
    DELETE = 'LANE_DELETE',
    RESTORE = 'LANE_RESTORE',
  }