export enum AvenueServiceCommands {
    GET_LIST_BY_PAGINATION = 'AVENUE_GET_LIST_BY_PAGINATION',
    GET_ALL_LIST = 'AVENUE_GET_ALL_LIST',
    GET_BY_ID = 'AVENUE_GET_BY_ID',
    CREATE = 'AVENUE_CREATE',
    CREATED = 'AVENUE_CREATED',
    UPDATE = 'AVENUE_UPDATE',
    DELETE = 'AVENUE_DELETE',
    RESTORE = 'AVENUE_RESTORE',
  }