export enum PassageServiceCommands {
    GET_LIST_BY_PAGINATION = 'PASSAGE_GET_LIST_BY_PAGINATION',
    GET_ALL_LIST = 'PASSAGE_GET_ALL_LIST',
    GET_BY_ID = 'PASSAGE_GET_BY_ID',
    CREATE = 'PASSAGE_CREATE',
    CREATED = 'PASSAGE_CREATED',
    UPDATE = 'PASSAGE_UPDATE',
    DELETE = 'PASSAGE_DELETE',
    RESTORE = 'PASSAGE_RESTORE',
  }