export enum CategoryServiceCommands {
  GET_LIST_BY_PAGINATION = 'CATEGORY_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'CATEGORY_GET_ALL_LIST',
  GET_BY_ID = 'CATEGORY_GET_BY_ID',
  CREATE = 'CATEGORY_CREATE',
  CREATED = 'CATEGOR_CREATED',
  UPDATE = 'CATEGORY_UPDATE',
  DELETE = 'CATEGORY_DELETE',
  RESTORE = 'CATEGORY_RESTORE',
}
