export enum PermissionServiceCommands {
  GET_LIST_BY_PAGINATION = 'PERMISSION_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'PERMISSION_GET_ALL_LIST',
  GET_BY_ID = 'PERMISSION_GET_BY_ID',
  CREATE = 'PERMISSION_CREATE',
  CREATED = 'PERMISSION_CREATED',
  UPDATE = 'PERMISSION_UPDATE',
  DELETE = 'PERMISSION_DELETE',
  RESTORE = 'PERMISSION_RESTORE',
}
