export enum SegmentServiceCommands {
  GET_LIST_BY_PAGINATION = 'SEGMENT_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'SEGMENT_GET_ALL_LIST',
  GET_BY_ID = 'SEGMENT_GET_BY_ID',
  CREATE = 'SEGMENT_CREATE',
  CREATED = 'SEGMENT_CREATED',
  UPDATE = 'SEGMENT_UPDATE',
  DELETE = 'SEGMENT_DELETE',
  RESTORE = 'SEGMENT_RESTORE',
}
