export enum RolePermissionServiceCommands {
  GET_LIST_BY_PAGINATION = 'ROLE_PERMISSION_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'ROLE_PERMISSION_GET_ALL_LIST',
  GET_BY_ID = 'ROLE_PERMISSION_GET_BY_ID',
  CREATE = 'ROLE_PERMISSION_CREATE',
  CREATED = 'ROLE_PERMISSION_CREATED',
  UPDATE = 'ROLE_PERMISSION_UPDATE',
  DELETE = 'ROLE_PERMISSION_DELETE',
  RESTORE = 'ROLE_PERMISSION_RESTORE',
}
