export enum StreetServiceCommands {
  GET_LIST_BY_PAGINATION = 'STREET_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'STREET_GET_ALL_LIST',
  GET_BY_ID = 'STREET_GET_BY_ID',
  CREATE = 'STREET_CREATE',
  CREATED = 'STREET_CREATED',
  UPDATE = 'STREET_UPDATE',
  DELETE = 'STREET_DELETE',
  RESTORE = 'STREET_RESTORE',
}
