export enum MainOrganizationServiceCommands {
  GET_LIST_BY_PAGINATION = 'MAIN_ORGANIZATION_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'MAIN_ORGANIZATION_GET_ALL_LIST',
  GET_BY_ID = 'MAIN_ORGANIZATION_GET_BY_ID',
  CREATE = 'MAIN_ORGANIZATION_CREATE',
  CREATED = 'MAIN_ORGANIZATION_CREATED',
  UPDATE = 'MAIN_ORGANIZATION_UPDATE',
  DELETE = 'MAIN_ORGANIZATION_DELETE',
  RESTORE = 'MAIN_ORGANIZATION_RESTORE',
}
