export enum RegionServiceCommands {
  GET_LIST_BY_PAGINATION = 'REGION_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'REGION_GET_ALL_LIST',
  GET_BY_ID = 'REGION_GET_BY_ID',
  CREATE = 'REGION_CREATE',
  CREATED = 'REGION_CREATED',
  UPDATE = 'REGION_UPDATE',
  DELETE = 'REGION_DELETE',
  RESTORE = 'REGION_RESTORE',
}
