export enum ResidentialAreaCommands {
    GET_LIST_BY_PAGINATION = 'RESIDENTIAL_AREA_GET_LIST_BY_PAGINATION',
    GET_ALL_LIST = 'RESIDENTIAL_AREA_GET_ALL_LIST',
    GET_BY_ID = 'RESIDENTIAL_AREA_GET_BY_ID',
    CREATE = 'RESIDENTIAL_AREA_CREATE',
    CREATED = 'RESIDENTIAL_AREA_CREATED',
    UPDATE = 'RESIDENTIAL_AREA_UPDATE',
    DELETE = 'RESIDENTIAL_AREA_DELETE',
    RESTORE = 'RESIDENTIAL_AREA_RESTORE',
  }