export enum DistrictServiceCommands {
  GET_LIST_BY_PAGINATION = 'DISTRICT_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'DISTRICT_GET_ALL_LIST',
  GET_BY_ID = 'DISTRICT_GET_BY_ID',
  CREATE = 'DISTRICT_CREATE',
  CREATED = 'DISTRICT_CREATED',
  UPDATE = 'DISTRICT_UPDATE',
  DELETE = 'DISTRICT_DELETE',
  RESTORE = 'DISTRICT_RESTORE',
}
  
  