export enum PhoneTypeServiceCommands {
  GET_LIST_BY_PAGINATION = 'PHONE_TYPE_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'PHONE_TYPE_GET_ALL_LIST',
  GET_BY_ID = 'PHONE_TYPE_GET_BY_ID',
  CREATE = 'PHONE_TYPE_CREATE',
  CREATED = 'PHONE_TYPE_CREATED',
  UPDATE = 'PHONE_TYPE_UPDATE',
  DELETE = 'PHONE_TYPE_DELETE',
  RESTORE = 'PHONE_TYPE_RESTORE',
}
