export enum BusinessServiceCommands {
  GET_LIST_BY_PAGINATION = 'BUSINESS_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'BUSINESS_GET_ALL_LIST',
  GET_WITH_NAME = 'BUSINESS_GET_WITH_NAME',
  GET_BY_ID = 'BUSINESS_GET_BY_ID',
  CREATE = 'BUSINESS_CREATE',
  UPDATE = 'BUSINESS_UPDATE',
  DELETE = 'BUSINESS_DELETE',
  RESTORE = 'BUSINESS_RESTORE',
}
