export enum AdditionalContentServiceCommands {
  GET_LIST_BY_PAGINATION = 'ADDITIONAL_CONTENT_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'ADDITIONAL_CONTENT_GET_ALL_LIST',
  GET_BY_ID = 'ADDITIONAL_CONTENT_GET_BY_ID',
  CREATE = 'ADDITIONAL_CONTENT_CREATE',
  UPDATE = 'ADDITIONAL_CONTENT_UPDATE',
  DELETE = 'ADDITIONAL_CONTENT_DELETE',
  RESTORE = 'ADDITIONAL_CONTENT_RESTORE',
}
