export enum VillageServiceCommands {
    GET_LIST_BY_PAGINATION = 'VILLAGE_GET_LIST_BY_PAGINATION',
    GET_ALL_LIST = 'VILLAGE_GET_ALL_LIST',
    GET_BY_ID = 'VILLAGE_GET_BY_ID',
    CREATE = 'VILLAGE_CREATE',
    CREATED = 'VILLAGE_CREATED',
    UPDATE = 'VILLAGE_UPDATE',
    DELETE = 'VILLAGE_DELETE',
    RESTORE = 'VILLAGE_RESTORE',
  }