export enum NearbyServiceCommands {
  GET_LIST_BY_PAGINATION = 'NEARBY_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'NEARBY_GET_ALL_LIST',
  GET_BY_ID = 'NEARBY_GET_BY_ID',
  CREATE = 'NEARBY_CREATE',
  CREATED = 'NEARBY_CREATED',
  UPDATE = 'NEARBY_UPDATE',
  DELETE = 'NEARBY_DELETE',
  RESTORE = 'NEARBY_RESTORE',
}
  
  