export enum RoleServiceCommands {
  GET_LIST_BY_PAGINATION = 'ROLE_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'ROLE_GET_ALL_LIST',
  GET_BY_ID = 'ROLE_GET_BY_ID',
  CREATE = 'ROLE_CREATE',
  CREATED = 'ROLE_CREATED',
  UPDATE = 'ROLE_UPDATE',
  DELETE = 'ROLE_DELETE',
  RESTORE = 'ROLE_RESTORE',
}
