export enum AdditionalServiceCommands {
  GET_LIST_BY_PAGINATION = 'ADDITIONAL_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'ADDITIONAL_GET_ALL_LIST',
  GET_BY_ID = 'ADDITIONAL_GET_BY_ID',
  CREATE = 'ADDITIONAL_CREATE',
  UPDATE = 'ADDITIONAL_UPDATE',
  DELETE = 'ADDITIONAL_DELETE',
  RESTORE = 'ADDITIONAL_RESTORE',
}
