export enum MonitoringServiceCommands {
  GET_LIST_BY_PAGINATION = 'MONITORING_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'MONITORING_GET_ALL_LIST',
  GET_BY_ID = 'MONITORING_GET_BY_ID',
  CREATE = 'MONITORING_CREATE',
  CREATED = 'MONITORING_CREATED',
  UPDATE = 'MONITORING_UPDATE',
  DELETE = 'MONITORING_DELETE',
  RESTORE = 'MONITORING_RESTORE',
}
