export enum ImpasseServiceCommands {
    GET_LIST_BY_PAGINATION = 'IMPASSE_GET_LIST_BY_PAGINATION',
    GET_ALL_LIST = 'IMPASSE_GET_ALL_LIST',
    GET_BY_ID = 'IMPASSE_GET_BY_ID',
    CREATE = 'IMPASSE_CREATE',
    CREATED = 'IMPASSE_CREATED',
    UPDATE = 'IMPASSE_UPDATE',
    DELETE = 'IMPASSE_DELETE',
    RESTORE = 'IMPASSE_RESTORE',
  }