export enum NeighborhoodCommands {
  GET_LIST_BY_PAGINATION = 'NEIGHBORHOOD_AREA_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'NEIGHBORHOOD_AREA_GET_ALL_LIST',
  GET_BY_ID = 'NEIGHBORHOOD_AREA_GET_BY_ID',
  CREATE = 'NEIGHBORHOOD_AREA_CREATE',
  CREATED = 'NEIGHBORHOOD_AREA_CREATED',
  UPDATE = 'NEIGHBORHOOD_AREA_UPDATE',
  DELETE = 'NEIGHBORHOOD_AREA_DELETE',
  RESTORE = 'NEIGHBORHOOD_AREA_RESTORE',
}