export enum AdditionalCategoryServiceCommands {
  GET_LIST_BY_PAGINATION = 'ADDITIONAL_CATEGORY_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'ADDITIONAL_CATEGORY_GET_ALL_LIST',
  GET_BY_ID = 'ADDITIONAL_CATEGORY_GET_BY_ID',
  CREATE = 'ADDITIONAL_CATEGORY_CREATE',
  UPDATE = 'ADDITIONAL_CATEGORY_UPDATE',
  DELETE = 'ADDITIONAL_CATEGORY_DELETE',
  RESTORE = 'ADDITIONAL_CATEGORY_RESTORE',
}
