export enum NearbyCategoryServiceCommands {
  GET_LIST_BY_PAGINATION = 'NEARBY_CATEGORY_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'NEARBY_CATEGORY_GET_ALL_LIST',
  GET_BY_ID = 'NEARBY_CATEGORY_GET_BY_ID',
  CREATE = 'NEARBY_CATEGORY_CREATE',
  CREATED = 'NEARBY_CATEGOR_CREATED',
  UPDATE = 'NEARBY_CATEGORY_UPDATE',
  DELETE = 'NEARBY_CATEGORY_DELETE',
  RESTORE = 'NEARBY_CATEGORY_RESTORE',
}
