export enum AreaServiceCommands {
    GET_LIST_BY_PAGINATION = 'AREA_GET_LIST_BY_PAGINATION',
    GET_ALL_LIST = 'AREA_GET_ALL_LIST',
    GET_BY_ID = 'AREA_GET_BY_ID',
    CREATE = 'AREA_CREATE',
    CREATED = 'AREA_CREATED',
    UPDATE = 'AREA_UPDATE',
    DELETE = 'AREA_DELETE',
    RESTORE = 'AREA_RESTORE',
  }