export enum SavedOrganizationCommands {
  GET_LIST_BY_PAGINATION = 'SAVED_ORGANIZATION_GET_LIST_BY_PAGINATION',
  GET_ALL_LIST = 'SAVED_ORGANIZATION_GET_ALL_LIST',
  GET_BY_ID = 'SAVED_ORGANIZATION_GET_BY_ID',
  CREATE = 'SAVED_ORGANIZATION_CREATE',
  CREATED = 'SAVED_ORGANIZATION_CREATED',
  UPDATE = 'SAVED_ORGANIZATION_UPDATE',
  DELETE = 'SAVED_ORGANIZATION_DELETE',
  RESTORE = 'SAVED_ORGANIZATION_RESTORE',
}
